### ISSUE TITLE
Let me choose between exploration and preview builds

### ISSUE THREAD

**Issue by sotakal** [mattpilott/teams-m1#1]
Microsoft has finally introduced the ARM build within their preview builds, so now users/visitors of the site may want to prefer to download a more stable version of the app (i.e. the preview build).

And thanks for creating the website!

**Comment by mattpilott** [comment]
Hey @sotakal I have added an option to select between the available builds and defaulted it to the preview one.

e8967e70e44582f6b31d2bde1c500987b7ef4ad3

Thanks for the suggestion
